# Email Parser Configuration
logging:
  level: INFO
  file: logs/email_parser.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

parser:
  supported_extensions:
    - .msg
  
  entity_patterns:
    emails: '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    phones: '(\+\d{1,3}[-.]?)?\(?\d{3}\)?[-.]?\d{3}[-.]?\d{4}'
    dates: '\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b|\b\d{4}[/-]\d{1,2}[/-]\d{1,2}\b'
    urls: 'http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+'
    money: '\$\d+(?:,\d{3})*(?:\.\d{2})?|\d+(?:,\d{3})*(?:\.\d{2})?\s*(?:USD|EUR|GBP|dollars?)'

mcp:
  server_name: "email-parser"
  server_version: "1.0.0"
